<?php
/**
 * PaymentTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * e-MCF
 *
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PaymentTypeEnum Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentTypeEnum
{
    /**
     * Possible values of this enum
     */
    const ESPECES = 'ESPECES';
const VIREMENT = 'VIREMENT';
const CARTEBANCAIRE = 'CARTEBANCAIRE';
const MOBILEMONEY = 'MOBILEMONEY';
const CHEQUES = 'CHEQUES';
const CREDIT = 'CREDIT';
const AUTRE = 'AUTRE';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ESPECES,
self::VIREMENT,
self::CARTEBANCAIRE,
self::MOBILEMONEY,
self::CHEQUES,
self::CREDIT,
self::AUTRE,        ];
    }
}
